name: build

run-name: Build and Test GoLang binary

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: write

    steps:
      # debug
      - name: Dump env
        run: env | sort
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # get all tags, needed to get git log
          ref: main

      # Go environment
      - name: setup Go Lang
        uses: actions/setup-go@v3
        with:
          go-version: '^1.21'
      - run: |
          go version
          go mod tidy
          go build -ldflags "-X main.Version=${GITHUB_REF_NAME} -X main.BuiltBy=github-actions" -o leeroy .